image: nixos/nix:1.11

before_script:
  - nix-env -iA nixpkgs.nixops

cache:
  paths:
    - ~/.nixops/
    - /nix

stages:
  # - build
  - deploy

#build:
#  script:
#    - nixops create ./servers/probitc-conf/cx10-hetzner-probitc.nix ./servers/probitc-conf/probitc.nix -d probitc
#    - nixops list
#  stage: build

deploy:
  script:
    - nixops create ./servers/probitc-conf/cx10-hetzner-probitc.nix ./servers/probitc-conf/probitc.nix -d probitc
    - nixops deploy -d probitc
  stage: deploy
